disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - identifier_name
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - WolmoCoreTests
line_length:
  warning: 200
  ignores_comments: true
function_body_length: 20
# allowed_symbols not working: https://github.com/realm/SwiftLint/issues/1762
# So disabling identifier_name rule
# identifier_name:
#   min_length:
#     error: 3
#   excluded:
#     # Less than minimum
#     - id
#     - iD
#     - ID
#     ## Indexes
#     - i
#     - j
#     # Not camel case
#     - URL
#   allowed_symbols:
#     - "_"
