branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode10.2
cache:
  - cocoapods
env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=Lint
    - TEST_TYPE=Samples
    - TEST_TYPE=CocoaPods
    - TEST_TYPE=Carthage
before_install: sh scripts/travis/before_install.sh
install: sh scripts/travis/install.sh
script: sh scripts/travis/script.sh
